spring:
  application:
    name: smalify
  profiles:
    active:
    - dev

  #H2 DB 
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#  datasource:
#    url: jdbc:h2:mem:smalify
